from class_pet import Dog

dog1 = Dog(name="Felix", gender="male", age=2)
dog2 = Dog(name="Linda", gender="female", age=2)
dog3 = Dog(name="Mouhtar", gender="male", age=0)

print("Kind of pet:", dog1.get_kind())
print("Name:", dog1.get_name())
print("Gender:", dog1.get_gender())
print("Age:", dog1.get_age())
print()
print("Kind of pet:", dog2.get_kind())
print("Name:", dog2.get_name())
print("Gender:", dog2.get_gender())
print("Age:", dog2.get_age())
print()
print("Kind of pet:", dog3.get_kind())
print("Name:", dog3.get_name())
print("Gender:", dog3.get_gender())
print("Age:", dog3.get_age())