# Generated by Django 3.2.3 on 2021-05-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='image_post',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
