# Generated by Django 3.1.7 on 2021-03-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20210327_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackuser',
            name='is_stuff',
            field=models.BooleanField(default=0),
        ),
    ]
