# Generated by Django 3.1.7 on 2021-03-30 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackuser',
            old_name='slack_category_post',
            new_name='slack_category',
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='actions.category'),
            preserve_default=False,
        ),
    ]
