# Generated by Django 3.1.7 on 2021-03-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_auto_20210330_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_header', models.TextField()),
                ('post_text', models.TextField()),
                ('post_category', models.ManyToManyField(blank=True, to='actions.Category')),
            ],
        ),
    ]
