# Generated by Django 3.1.7 on 2021-03-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
    ]
