# Generated by Django 3.1.7 on 2021-03-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_remove_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_link',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
