# Generated by Django 3.1.7 on 2021-03-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_post_post_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channel_category',
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_category',
            field=models.ManyToManyField(blank=True, to='actions.Category'),
        ),
    ]
